version: "3"
services:
  gateway-server:
    image: gateway:1.0.0
    hostname: gateway-server
    networks:
      - network
    ports:
      - "7000:7000"
  websocket-server:
    image: websocket:1.0.0
    hostname: websocket-serverr
    networks:
      - network
networks:
  network:
    external:
      name: compose-network